import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scanpy as sc
from adjustText import adjust_text
from analysis_contract import (
    DEFAULT_EXPRESSION_LAYER,
    get_expression_matrix,
    load_nmf_artifacts,
    require_data_contract,
)

# ==========================================
# 1. 路径和字体配置 (Nature 风格)
# ==========================================
plt.rcParams['pdf.fonttype'] = 42
plt.rcParams['ps.fonttype'] = 42
plt.rcParams['font.sans-serif'] = ['Arial', 'Helvetica', 'DejaVu Sans']
plt.rcParams['figure.dpi'] = 300
plt.rcParams['savefig.dpi'] = 600

base_dir = r"d:\Data_Analysis\空间转录组分析\ST_analysis\New_Analysis"
sys.path.append(base_dir)
from analysis_config import *

out_dir = PIPELINE_FILES["core_genes_dir"]
os.makedirs(out_dir, exist_ok=True)

# 核心 28 个基因 (根据之前的筛选)
core_genes = [
    'EPHA3', 'EPHA5', 'EPHA6', 'EFNA5', 'PLXNA4', 'LAMB1', 'TNR',
    'GABRA5', 'GABRG3', 'SLC35F3', 
    'CNTN3', 'CNTN4', 'CNTN5', 'CNTNAP2', 'CNTNAP5', 
    'CDH9', 'CDH12', 'CDH18', 'CDH22',
    'ROBO1', 'ROBO2', 'LRP1B', 'LRP8', 'NCAM2'
]

# ==========================================
# 2. 读取 Step 07 已保存的统一 NMF 结果，禁止在下游重跑另一版 NMF
# ==========================================
print("Loading spatial data for NMF weight extraction...")
adata_spatial = sc.read_h5ad(PIPELINE_FILES["annotated_h5ad"])
require_data_contract(adata_spatial, "10_Core_Genes_Visualization.py")

print("Loading Combined_AllSamples NMF artifacts generated by Step 07...")
_, gene_weights, metadata, _ = load_nmf_artifacts(PIPELINE_FILES["nmf_dir"], "Combined_AllSamples")
factor7_col = 'Factor_7'
if factor7_col not in gene_weights.columns:
    raise RuntimeError(f"Missing `{factor7_col}` in saved NMF gene weights.")

df_nmf_weights = pd.DataFrame({
    'gene': gene_weights.index,
    'Factor7_Weight': gene_weights[factor7_col].values
})

del adata_spatial # 释放内存

# ==========================================
# 3. 读取单细胞 DEG 结果并合并数据
# ==========================================
print("Loading Single-Cell DEGs...")
deg_dir = PIPELINE_FILES["deg_dir"]
deg_file = os.path.join(deg_dir, "DE_DN_Excit_vs_Normal_Excit.csv")
df_deg = pd.read_csv(deg_file)

# 合并两张表 (取交集基因集)
df_merge = pd.merge(df_deg, df_nmf_weights, on='gene', how='inner')

# 标记 197 个重叠基因 (即 Factor 7 top200 且 DEG显著上调的)
overlap_file = os.path.join(out_dir, "Overlap_Factor7_and_DNExcit_DEGs.txt")
with open(overlap_file, "r") as f:
    overlap_genes = set([g.strip() for g in f.readlines()[1].strip().split(",") if g.strip()])

df_merge['is_overlap'] = df_merge['gene'].isin(overlap_genes)
df_merge['is_core'] = df_merge['gene'].isin(core_genes)

# ==========================================
# 4. 绘制双指标散点图 (Dual-metric Scatter Plot)
# ==========================================
print("Plotting Dual-metric Scatter Plot...")
plt.figure(figsize=(9, 7))

# 绘制背景点 (灰色, 透明度高)
bg_data = df_merge[~df_merge['is_overlap']]
plt.scatter(bg_data['logfoldchanges'], bg_data['Factor7_Weight'], 
            c='lightgrey', alpha=0.3, s=15, edgecolors='none', label='Background Genes')

# 绘制重叠基因 (红色)
ov_data = df_merge[df_merge['is_overlap'] & ~df_merge['is_core']]
plt.scatter(ov_data['logfoldchanges'], ov_data['Factor7_Weight'], 
            c='#E64B35', alpha=0.8, s=40, edgecolors='white', linewidth=0.5, label='Overlap Genes (n=197)')

# 绘制核心基因 (大号橙点/绿点等)
core_data = df_merge[df_merge['is_core']]
plt.scatter(core_data['logfoldchanges'], core_data['Factor7_Weight'], 
            c='#4DBBD5', alpha=1.0, s=80, edgecolors='black', linewidth=1, label='Core Targets (n=24)')

# 添加十字辅助线
plt.axvline(x=0.5, color='black', linestyle='--', linewidth=1, alpha=0.5)
plt.axhline(y=np.percentile(df_merge['Factor7_Weight'], 99), color='black', linestyle='--', linewidth=1, alpha=0.5)

# 添加核心基因文本标签 (利用 adjustText 防止重叠)
texts = []
for i, row in core_data.iterrows():
    texts.append(plt.text(row['logfoldchanges'], row['Factor7_Weight'], row['gene'], 
                          fontsize=9, fontweight='bold', color='#333333'))

from adjustText import adjust_text
adjust_text(texts, arrowprops=dict(arrowstyle="-", color="gray", lw=0.5, alpha=0.8))

plt.xlabel("Single-Cell Log2 Fold Change\n(DN Excitatory vs Normal Excitatory)", fontweight='bold', fontsize=12)
plt.ylabel("Spatial NMF Factor 7 Weight\n(Pathogenic Niche Dominance)", fontweight='bold', fontsize=12)
plt.title("Dual-metric Verification of Core Pathogenic Genes in TSC", fontweight='bold', fontsize=14)
plt.legend(loc='upper left', frameon=True)
sns.despine()

plt.tight_layout()
plt.savefig(os.path.join(out_dir, "Dual_Metric_ScatterPlot_CoreGenes.pdf"))
plt.savefig(os.path.join(out_dir, "Dual_Metric_ScatterPlot_CoreGenes.png"))
plt.close()

# ==========================================
# 5. 绘制复杂热图 (Complex Annotated Heatmap)
# ==========================================
print("Plotting Complex Heatmap from Single-Cell Data...")
sc_adata_path = PIPELINE_FILES["annotated_h5ad"]
adata_sc = sc.read_h5ad(sc_adata_path)

# 提取 Excitatory DN 和 Normal Excitatory
dn_types = [c for c in adata_sc.obs['celltype'].unique() if 'Dysmorphic' in str(c) and 'Excit' in str(c)]
normal_types = [c for c in adata_sc.obs['celltype'].unique() if 'Neuron' in str(c) and 'Excitatory' in str(c) and 'Dysmorphic' not in str(c)]

adata_sub = adata_sc[adata_sc.obs['celltype'].isin(dn_types + normal_types)].copy()
adata_sub.obs['Group'] = 'Normal Excitatory'
adata_sub.obs.loc[adata_sub.obs['celltype'].isin(dn_types), 'Group'] = 'Excitatory DN'

# 为了热图的美观，每组随机下采样 500 个细胞
sc.pp.subsample(adata_sub, n_obs=min(1000, len(adata_sub)), random_state=42)
adata_sub = adata_sub[adata_sub.obs.sort_values('Group', ascending=False).index].copy()

# 提取核心基因的表达矩阵
valid_core_genes = [g for g in core_genes if g in adata_sub.var_names]
expr_mat = get_expression_matrix(adata_sub, layer=DEFAULT_EXPRESSION_LAYER, nonnegative=False)
expr_mat = expr_mat[:, [adata_sub.var_names.get_loc(g) for g in valid_core_genes]]

# 对基因进行 Z-score 标准化
from scipy.stats import zscore
expr_z = zscore(expr_mat, axis=0)
expr_z = np.clip(expr_z, -2.5, 2.5) # 截断极端值

df_expr = pd.DataFrame(expr_z.T, index=valid_core_genes, columns=adata_sub.obs.index)

# 准备列注释 (Cell Group)
col_colors = adata_sub.obs['Group'].map({'Excitatory DN': '#E64B35', 'Normal Excitatory': '#4DBBD5'})

# 绘制 Clustermap
g = sns.clustermap(df_expr, cmap='viridis', col_colors=col_colors,
                   row_cluster=True, col_cluster=False, # 保持细胞分组的顺序
                   xticklabels=False, yticklabels=True,
                   figsize=(12, 8), cbar_kws={'label': 'Z-scored Expression'},
                   dendrogram_ratio=(0.1, 0.0))

# 添加图例
from matplotlib.patches import Patch
handles = [Patch(facecolor='#E64B35', label='Excitatory DN'),
           Patch(facecolor='#4DBBD5', label='Normal Excitatory')]
plt.legend(handles=handles, title='Cell Type', bbox_to_anchor=(1.2, 1), loc='upper left')

g.fig.suptitle("Expression of 24 Dual-Verified Core Genes at Single-Cell Resolution", y=1.02, fontweight='bold', fontsize=14)

plt.savefig(os.path.join(out_dir, "Complex_Heatmap_CoreGenes.pdf"), bbox_inches='tight')
plt.savefig(os.path.join(out_dir, "Complex_Heatmap_CoreGenes.png"), bbox_inches='tight')
plt.close()

print("All plots successfully generated!")
